[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-cron"

  [plugins.inputs]
    crons = [
      { schedule = "0 */6 * * *", function = "voxxee-seed" }
    ]
